theme: jekyll-theme-merlot
title: [eg]

# Site settings
description: [This is a sample repo of gh-pages for a project.]

# Site settings
username: Github ScorpionVT
user_description: CS student

# Build settings
markdown: kramdown

